import Onyx from 'react-native-onyx';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import waitForBatchedUpdatesWithAct from '../utils/waitForBatchedUpdatesWithAct';

// Mock CONFIG so IS_HYBRID_APP is true, which is required for signInToOldDotAndChooseExperience to proceed
jest.mock('@src/CONFIG', () => {
    const realConfig = jest.requireActual<{default: Record<string, unknown>}>('@src/CONFIG').default;
    return {__esModule: true, default: {...realConfig, IS_HYBRID_APP: true}};
});

// Mock Log to avoid network calls in unit tests
const mockLog = {info: jest.fn(), hmmm: jest.fn(), warn: jest.fn(), alert: jest.fn(), client: jest.fn()};
jest.mock('@libs/Log', () => ({__esModule: true, default: mockLog}));

// Mock TryNewDotUtils
jest.mock('@libs/TryNewDotUtils', () => ({
    shouldUseOldApp: jest.fn().mockReturnValue(false),
    isLockedToNewApp: jest.fn().mockReturnValue(false),
    shouldBlockOldAppExit: jest.fn().mockReturnValue(false),
}));

// Mock Network/NetworkStore
jest.mock('@libs/Network/NetworkStore', () => ({getCurrentUserEmail: jest.fn().mockReturnValue('test@example.com')}));

Onyx.init({keys: ONYXKEYS});

// Import HybridApp to register its Onyx subscribers (side-effect-only import)
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('@libs/HybridApp');

type HybridAppModuleType = {
    signInToOldDot: (args: {
        autoGeneratedLogin: string;
        autoGeneratedPassword: string;
        authToken: string;
        email: string;
        policyID: string;
        signingInWithSAML: boolean;
    }) => void;
    isHybridApp: () => boolean;
};

describe('HybridApp signInToOldDot deduplication', () => {
    const {default: HybridAppModule} = require('@expensify/react-native-hybrid-app') as {default: HybridAppModuleType};
    let signInToOldDotSpy: jest.SpiedFunction<HybridAppModuleType['signInToOldDot']>;

    beforeEach(async () => {
        jest.clearAllMocks();
        signInToOldDotSpy = jest.spyOn(HybridAppModule, 'signInToOldDot').mockImplementation(() => {});
        // Reset module-level isSigningInToOldDot flag between tests by resetting session
        await Onyx.clear();
        await waitForBatchedUpdatesWithAct();
        // Trigger a session change to reset the in-memory guard
        await Onyx.set(ONYXKEYS.SESSION, {accountID: undefined});
        await waitForBatchedUpdatesWithAct();
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    it('calls signInToOldDot only once when multiple Onyx subscribers fire concurrently', async () => {
        const CONFIG = require('@src/CONFIG').default as {IS_HYBRID_APP: boolean};
        expect(CONFIG.IS_HYBRID_APP).toBe(true);

        // Set up the initial state that satisfies all guards except one key to avoid premature trigger
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
            [ONYXKEYS.SESSION]: {accountID: 1, authToken: 'test-auth-token', authTokenType: undefined},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
        });
        await waitForBatchedUpdatesWithAct();

        // signInToOldDot should not fire yet — CREDENTIALS is missing
        expect(signInToOldDotSpy).not.toHaveBeenCalled();

        // Setting CREDENTIALS satisfies the last guard. Because all other Onyx subscribers have
        // already fired and cached their current values, setting CREDENTIALS triggers
        // signInToOldDotAndChooseExperience once from the CREDENTIALS subscriber,
        // and no other subscriber fires again. The isSigningInToOldDot flag prevents
        // any duplicate call that could occur if multiple keys update simultaneously.
        await Onyx.set(ONYXKEYS.CREDENTIALS, {autoGeneratedLogin: 'login', autoGeneratedPassword: 'password'});
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).toHaveBeenCalledTimes(1);
    });

    it('resets the guard when the session account changes, allowing sign-in for the new account', async () => {
        // First sign-in
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
            [ONYXKEYS.SESSION]: {accountID: 1, authToken: 'auth-token-1', authTokenType: undefined},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
        });
        await waitForBatchedUpdatesWithAct();
        await Onyx.set(ONYXKEYS.CREDENTIALS, {autoGeneratedLogin: 'login1', autoGeneratedPassword: 'password1'});
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).toHaveBeenCalledTimes(1);
        jest.clearAllMocks();

        // Sign out — clear session and credentials so the guard can reset
        await Onyx.multiSet({
            [ONYXKEYS.SESSION]: {accountID: undefined, authToken: undefined},
            [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: undefined, autoGeneratedPassword: undefined},
        });
        await waitForBatchedUpdatesWithAct();

        // Sign in as a different account — guard must reset on accountID change
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
            [ONYXKEYS.SESSION]: {accountID: 2, authToken: 'auth-token-2', authTokenType: undefined},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
        });
        await waitForBatchedUpdatesWithAct();
        await Onyx.set(ONYXKEYS.CREDENTIALS, {autoGeneratedLogin: 'login2', autoGeneratedPassword: 'password2'});
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).toHaveBeenCalledTimes(1);
    });

    it('does not call signInToOldDot when autoAuthState is SIGNING_IN', async () => {
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
            [ONYXKEYS.SESSION]: {accountID: 1, authToken: 'auth-token', authTokenType: undefined, autoAuthState: CONST.AUTO_AUTH_STATE.SIGNING_IN},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
            [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: 'login', autoGeneratedPassword: 'password'},
        });
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).not.toHaveBeenCalled();
    });

    it('does not call signInToOldDot when credentials are incomplete', async () => {
        await Onyx.multiSet({
            [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
            [ONYXKEYS.SESSION]: {accountID: 1, authToken: 'auth-token', authTokenType: undefined},
            [ONYXKEYS.ACCOUNT]: {requiresTwoFactorAuth: false, needsTwoFactorAuthSetup: false},
            [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: 'login'}, // missing autoGeneratedPassword
        });
        await waitForBatchedUpdatesWithAct();

        expect(signInToOldDotSpy).not.toHaveBeenCalled();
    });
});
